import infer

ldac = infer.LightDetectionAndClassification(detection_model = infer.Detection_Model.SSD_MOBILE_NET)

desired_labels=["Red", "Green", "Yellow"]
print("\n\n\n")
ldac.infer_and_save("traffic.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic2.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic3.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic4.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic5.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic6.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic7.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic8.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic9.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic10.jpg", desired_labels=desired_labels)

print("\n\n\n")
ldac.infer_and_save("left0000.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("left0003.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("left0011.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("left0027.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("left0140.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("left0701.jpg", desired_labels=desired_labels)

