import infer

ldac = infer.LightDetectionAndClassification(detection_model = infer.Detection_Model.RCNN_RESNET_101)

desired_labels=["Red", "Green", "Yellow"]
print("\n\n\n")
ldac.infer_and_save("traffic.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic2.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic3.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic4.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic5.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic6.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic7.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic8.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic9.jpg", desired_labels=desired_labels)
print("\n\n\n")
ldac.infer_and_save("traffic10.jpg", desired_labels=desired_labels)
